package com.dxsoft.rsgzgl.retirement;

public record RetirementRetireeUpdateRequest(
        String name,
        String gender,
        String idCard,
        String nation,
        String birthYearMonth,
        String workStartYearMonth,
        Integer interruptedYears,
        Integer salaryYears,
        String education,
        String retirementCategory,
        String retirementDate,
        String retirementReason,
        String postCategory,
        String positionCode,
        String positionName,
        String gradeLevel,
        String gradeStep,
        String salaryStandardYearMonth,
        String allowanceStandardYearMonth,
        String approvalOrganization,
        Integer teachingRaisePercentage,
        Integer teachingYears,
        Integer increaseRatio,
        String increaseReason,
        String approvalDocumentNumber,
        String interruptedNote,
        String interruptedMonths,
        String bankAccount,
        Integer teachingRaise,
        Integer rankAllowance,
        Integer bonusBalance) {
}
