package com.dxsoft.rsgzgl.ops.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class OpsSchemaInitializer {

    private final JdbcTemplate jdbcTemplate;
    private final PasswordEncoder passwordEncoder;
    private final String adminUsername;
    private final String adminPassword;
    private final boolean resetAdminPassword;

    OpsSchemaInitializer(
            JdbcTemplate jdbcTemplate,
            PasswordEncoder passwordEncoder,
            @Value("${rsgzgl.ops.admin.username:ops}") String adminUsername,
            @Value("${rsgzgl.ops.admin.password:ops123}") String adminPassword,
            @Value("${rsgzgl.ops.admin.reset-password:true}") boolean resetAdminPassword) {
        this.jdbcTemplate = jdbcTemplate;
        this.passwordEncoder = passwordEncoder;
        this.adminUsername = adminUsername;
        this.adminPassword = adminPassword;
        this.resetAdminPassword = resetAdminPassword;
        initialize();
    }

    private void initialize() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ops_admin (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(80) NOT NULL UNIQUE,
                    password_hash VARCHAR(120) NOT NULL,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ukey_device (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    chip_id VARCHAR(64) NOT NULL UNIQUE,
                    sm2_user_id VARCHAR(128),
                    pubkey_x VARCHAR(64),
                    pubkey_y VARCHAR(64),
                    enc_algo_key VARCHAR(64),
                    auth_modes VARCHAR(20),
                    username VARCHAR(80),
                    org_code VARCHAR(40),
                    note VARCHAR(500),
                    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                    provisioned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        ensureColumn("ukey_device", "enc_algo_key", "VARCHAR(64)");
        ensureColumn("ukey_device", "auth_modes", "VARCHAR(20)");
        // Allow SM2-less rows on existing DBs that created NOT NULL pubkey columns earlier
        try {
            jdbcTemplate.execute("ALTER TABLE ukey_device ALTER COLUMN sm2_user_id VARCHAR(128) NULL");
            jdbcTemplate.execute("ALTER TABLE ukey_device ALTER COLUMN pubkey_x VARCHAR(64) NULL");
            jdbcTemplate.execute("ALTER TABLE ukey_device ALTER COLUMN pubkey_y VARCHAR(64) NULL");
        } catch (Exception ignored) {
        }
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS license_org (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    organization_code VARCHAR(40) NOT NULL UNIQUE,
                    name VARCHAR(120) NOT NULL,
                    short_name VARCHAR(80),
                    property VARCHAR(40),
                    category VARCHAR(40),
                    payroll_category VARCHAR(40),
                    allowance_standard VARCHAR(40),
                    personnel_quota INT,
                    establishment_count INT,
                    actual_count INT,
                    organization_level VARCHAR(40),
                    system_category VARCHAR(40),
                    performance_allowance_enabled INT,
                    performance_category INT,
                    performance_ratio VARCHAR(40),
                    year_allowance_category INT,
                    finance_source VARCHAR(40),
                    housing_fund_withheld VARCHAR(20),
                    pension_withheld VARCHAR(20),
                    city VARCHAR(80),
                    supervisor VARCHAR(80),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        try {
            jdbcTemplate.execute("ALTER TABLE license_org ADD COLUMN system_category VARCHAR(40)");
        } catch (Exception ignored) {
        }
        try {
            jdbcTemplate.execute("ALTER TABLE license_org ADD COLUMN performance_ratio VARCHAR(40)");
        } catch (Exception ignored) {
        }
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS license_local_policy (
                    id INT PRIMARY KEY,
                    policy_json CLOB NOT NULL,
                    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS license_issue_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_username VARCHAR(80) NOT NULL,
                    subject_code VARCHAR(40) NOT NULL,
                    subject_name VARCHAR(120) NOT NULL,
                    expires_at VARCHAR(40),
                    organization_count INT NOT NULL,
                    fingerprint VARCHAR(64) NOT NULL,
                    summary VARCHAR(500) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS monitor_target (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(120) NOT NULL,
                    kind VARCHAR(20) NOT NULL DEFAULT 'HTTP',
                    url VARCHAR(500) NOT NULL,
                    timeout_ms INT NOT NULL DEFAULT 5000,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS monitor_snapshot (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    collected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    overall VARCHAR(20) NOT NULL,
                    cpu_percent DOUBLE,
                    memory_used_bytes BIGINT,
                    memory_total_bytes BIGINT,
                    disk_used_bytes BIGINT,
                    disk_total_bytes BIGINT,
                    load_average DOUBLE,
                    hostname VARCHAR(200),
                    detail CLOB
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS monitor_alert (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    level VARCHAR(20) NOT NULL,
                    title VARCHAR(200) NOT NULL,
                    message VARCHAR(1000) NOT NULL,
                    fingerprint VARCHAR(80) NOT NULL
                )
                """);
        seedAdmin();
    }

    private void ensureColumn(String table, String column, String definition) {
        try {
            Integer count = jdbcTemplate.queryForObject(
                    """
                    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE UPPER(TABLE_NAME) = UPPER(?) AND UPPER(COLUMN_NAME) = UPPER(?)
                    """,
                    Integer.class,
                    table,
                    column);
            if (count != null && count == 0) {
                jdbcTemplate.execute("ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
            }
        } catch (Exception ignored) {
        }
    }

    private void seedAdmin() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ops_admin WHERE username = ?",
                Integer.class,
                adminUsername);
        String hash = passwordEncoder.encode(adminPassword == null || adminPassword.isBlank() ? "ops123" : adminPassword);
        if (count == null || count == 0) {
            jdbcTemplate.update(
                    "INSERT INTO ops_admin (username, password_hash, enabled) VALUES (?, ?, TRUE)",
                    adminUsername,
                    hash);
        } else if (resetAdminPassword) {
            jdbcTemplate.update(
                    "UPDATE ops_admin SET password_hash = ?, enabled = TRUE WHERE username = ?",
                    hash,
                    adminUsername);
        }
    }
}
