CREATE TABLE IF NOT EXISTS dryjbxx (
    uid INTEGER PRIMARY KEY AUTO_INCREMENT,
    dwbm VARCHAR(9) NOT NULL,
    grbm VARCHAR(5) NOT NULL,
    xm VARCHAR(20) NOT NULL,
    sfzh VARCHAR(18),
    xb VARCHAR(2),
    csny VARCHAR(7),
    ryfl VARCHAR(20),
    dwsx VARCHAR(10),
    gwfl VARCHAR(20),
    cjgzny VARCHAR(7),
    zzny VARCHAR(7),
    gznx INTEGER DEFAULT 0,
    xlbm VARCHAR(10),
    zgxl VARCHAR(20),
    zwjb VARCHAR(20),
    zjbm VARCHAR(10),
    xrzw VARCHAR(30),
    rzny VARCHAR(7),
    mz VARCHAR(10),
    zzmm VARCHAR(20),
    dah VARCHAR(20),
    xckhndzw VARCHAR(4),
    xckhndjb VARCHAR(4),
    jx VARCHAR(20),
    jxjtbz VARCHAR(6),
    jxjt INTEGER DEFAULT 0,
    tc VARCHAR(8)
);

CREATE TABLE IF NOT EXISTS hisbase (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    sid VARCHAR(40),
    uid INTEGER,
    dwbm VARCHAR(9) NOT NULL,
    grbm VARCHAR(5) NOT NULL,
    xm VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS dryzwbh (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS dxl (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS dndkh (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS jx (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS dtgxx (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS tgqgz2006 (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
CREATE TABLE IF NOT EXISTS hjxx (id INTEGER PRIMARY KEY AUTO_INCREMENT, dwbm VARCHAR(9), grbm VARCHAR(5));
