package com.dxsoft.rsgzgl.payroll;

import java.util.List;

public record NewPersonnelSalaryDetail(
        Integer uid,
        String payrollHistoryId,
        String organizationCode,
        String organizationName,
        String personCode,
        String name,
        String joinYearMonth,
        String joinType,
        String workStartYearMonth,
        String changeType,
        String calculationPeriod,
        String pathNote,
        String positionCode,
        String positionName,
        String projectedLevel,
        String projectedStep,
        String executeLevel,
        String executeStep,
        String levelAssessmentStartYear,
        String stepAssessmentStartYear,
        Integer positionSalary,
        Integer gradeSalary,
        Integer performanceAllowance,
        Integer subsidyAllowance,
        Integer calculatedTotal,
        String tipLevel,
        String tipStep,
        String tipLevelAssessmentStartYear,
        String tipStepAssessmentStartYear,
        String tipPositionCode,
        String tipPositionName,
        Boolean tipBaseCleared,
        Integer tipPositionSalary,
        Integer tipGradeSalary,
        Integer tipPerformanceAllowance,
        Integer tipSubsidyAllowance,
        Integer tipTotal,
        String performanceAllowanceCaption,
        String subsidyAllowanceCaption,
        Boolean showSubsidyAllowance,
        String standardNote,
        Boolean applyEligible,
        Boolean rollbackEligible,
        List<String> explanationLines) {
}
