package com.dxsoft.rsgzgl.payroll;

import java.util.List;

public record RegularizationPreview(
        String payrollHistoryId,
        String organizationCode,
        String personCode,
        String name,
        String calculationPeriod,
        String probationPositionCode,
        String probationPositionName,
        String educationCode,
        String educationName,
        String graduationDate,
        String regularPositionCode,
        String regularPositionName,
        String regularLevel,
        String regularStep,
        String currentLevel,
        String currentStep,
        Integer currentPositionSalary,
        Integer currentGradeSalary,
        Integer currentTechnicalGradeSalary,
        Integer currentPerformanceAllowance,
        Integer currentSubsidyAllowance,
        Integer currentFloatingSalary,
        Integer currentSalary,
        Integer currentTotal,
        Integer regularPositionSalary,
        Integer regularBaseSalary,
        Integer regularTechnicalGradeSalary,
        Integer regularPerformanceAllowance,
        Integer regularSubsidyAllowance,
        Integer regularFloatingSalary,
        Integer totalRegularSalary,
        Integer regularTotal,
        Integer increaseAmount,
        String performanceAllowanceCaption,
        String subsidyAllowanceCaption,
        Boolean showSubsidyAllowance,
        Boolean eligible,
        String note,
        Boolean applyEligible,
        Boolean rollbackEligible,
        List<PayrollChangeComponentComparison> salaryComponents
) {
}
