package com.dxsoft.rsgzgl.payroll;

import java.util.List;

public record SalaryStandardAdjustmentPreview(
        String payrollHistoryId,
        String organizationCode,
        String organizationName,
        String personCode,
        String name,
        String calculationPeriod,
        String currentChangeType,
        String targetStandardYearMonth,
        String currentSalaryStandardYearMonth,
        String currentAllowanceStandardYearMonth,
        String targetAllowanceStandardYearMonth,
        String positionCode,
        String positionName,
        Integer currentPositionSalary,
        Integer currentGradeSalary,
        Integer currentTechnicalGradeSalary,
        Integer currentPerformanceAllowance,
        Integer currentSubsidyAllowance,
        Integer currentFloatingSalary,
        Integer currentTotal,
        Integer calculatedPositionSalary,
        Integer calculatedGradeSalary,
        Integer calculatedTechnicalGradeSalary,
        Integer calculatedPerformanceAllowance,
        Integer calculatedSubsidyAllowance,
        Integer calculatedFloatingSalary,
        Integer calculatedTotal,
        Integer differenceAmount,
        String standardNote,
        String gradeSalaryLabel,
        String performanceAllowanceCaption,
        String subsidyAllowanceCaption,
        Boolean showSubsidyAllowance,
        Boolean applyEligible,
        Boolean rollbackEligible,
        List<PayrollChangeComponentComparison> salaryComponents,
        Boolean midChainApply,
        Integer laterPeriodSuccessorCount) {
}
