package com.dxsoft.rsgzgl.report;

public record WageReform2006PublicNoticeRow(
        String id,
        String organizationCode,
        String organizationName,
        String personCode,
        String name,
        String workStartYearMonth,
        Integer schoolingYears,
        Integer minimumWorkYears,
        Integer deductionYears,
        Integer wageReformYears,
        String currentPositionCode,
        String currentPositionName,
        String currentAppointmentPeriod,
        Integer currentAppointmentYears,
        Integer currentPositionDeductionYears,
        String lowerPositionCode,
        String lowerPositionName,
        String lowerAppointmentPeriod,
        Integer lowerAppointmentYears,
        Integer lowerPositionDeductionYears,
        String educationCode,
        String educationName,
        String reformPositionCode,
        String reformPositionName,
        String reformLevel,
        String reformStep,
        Integer fixedStep,
        Integer pendingStep,
        Integer fixedLevel,
        Integer pendingLevel,
        String remark) {
}
